[package]
name = "cctui"
version = "1.1.2"
authors = ["Kevin James <KevinJames@thekev.in>"]
edition = "2018"

description = "CCTray TUI, a build monitoring dashboard for your terminal"
readme = "README.md"
repository = "https://github.com/TheKevJames/tools/tree/master/cctui"
license = "MIT"
keywords = ["cctray", "ci", "tui"]

[badges]
circle-ci = { repository = "TheKevJames/tools", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "=0.4.33"
config = { version = "=0.13.4", features = ["yaml"] }
fern = "=0.6.2"
log = "=0.4.20"
reqwest = { version = "=0.11.23", features = ["blocking", "json"] }
serde = { version = "=1.0.196", features = ["derive"] }
serde_json = "=1.0.112"
serde-xml-rs = "=0.6.0"
xdg = "=2.5.2"

ratatui = { version = "=0.25.0", default-features = false, features = ["termion"] }
termion = "=3.0.0"  # TODO: crossterm
# crossterm = "0.27.0"
