name: CI Builds

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read # This is required for actions/checkout
  packages: write

jobs:
  sanity_check:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run bash command
        run: echo hello
  build:
    name: Build docker image
    uses: PromiseNetwork/docker_tools_fork/.github/workflows/docker-build-image.yml@main
    with:
      dockerfile: "docker-gcloud-pubsub-emulator/Dockerfile"
      name: docker-gcloud-pubsub-emulator
      build_context: "./docker-gcloud-pubsub-emulator"
      tags: |
        ${{ github.ref == 'ref/heads/main' && 'latest' || null }}
        ${{ github.event.pull_request.number && format('pr-{0}', github.event.pull_request.number) || null }}